[General]
pause = ["esc", "F1"]
quit = ["q"]

[Movement]
left = ["left", "kp4"]
right = ["right", "kp6"]
down = ["down", "kp2"]

[Rotation]
cw = ["x", "up", "kp1", "kp5", "kp9"] # clockwise
ccw = ["ctrl", "z", "kp3", "kp7"]     # counter-clockwise

[Action]
hold = ["shift", "c", "kp0"]
drop = ["space", "kp5"]

[Sound]
music = true
volume = 0.5
