[General]
pause = ["esc", "F1"]
quit = ["q"]

[Movement]
left = ["left", "keypad 4"]
right = ["right", "keypad 6"]
down = ["down", "keypad 2"]

[Rotation]
cw = ["x", "up", "keypad 1", "keypad 5", "keypad 9"] # clockwise
ccw = [
  "left ctrl",
  "right ctrl",
  "z",
  "keypad 3",
  "keypad 7",
] # counter-clockwise

[Action]
hold = ["shift", "c", "keypad 0"]
drop = ["space", "keypad 5"]

[Volume.Music]
enabled = true
level = 0.01

[Volume.SFX]
enabled = true
level = 0.02
