name: Build Typst document
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: write
jobs:
  typst-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            typst/main.typ
      - name: Uplaoding PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            typst/main.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: typst/main.pdf
